[versions]
agp = "8.9.0"
kotlin = "2.0.21"
coreKtx = "1.16.0"
junit = "4.13.2"
junitVersion = "1.2.1"
espressoCore = "3.6.1"
lifecycleRuntimeKtx = "2.8.7"
activityCompose = "1.10.1"
composeBom = "2024.09.00"
appcompat = "1.7.0"
ktlint = "12.1.1"
material = "1.12.0"
google-service-ver = "4.4.2"
firebaseBom = "33.13.0"
crashlytic-ver = "3.0.3"
hilt-ver = "2.56.1"
ksp-ver = "2.0.21-1.0.27"
app-startup-ver = "1.2.0"
splash-screen-ver = "1.0.0"

#======================================== AndroidX =================================================
[libraries]
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
junit = { group = "junit", name = "junit", version.ref = "junit" }
androidx-junit = { group = "androidx.test.ext", name = "junit", version.ref = "junitVersion" }
androidx-espresso-core = { group = "androidx.test.espresso", name = "espresso-core", version.ref = "espressoCore" }
androidx-lifecycle-runtime-ktx = { group = "androidx.lifecycle", name = "lifecycle-runtime-ktx", version.ref = "lifecycleRuntimeKtx" }
androidx-activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activityCompose" }
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
androidx-app-startup = { module = "androidx.startup:startup-runtime", version.ref = "app-startup-ver" }
androidx-splash-screen = { module = "androidx.core:splashscreen", version.ref = "splash-screen-ver" }
#======================================== Material =================================================
androidx-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
#======================================== Google Service ===========================================
firebase-bom = { module = "com.google.firebase:firebase-bom", version.ref = "firebaseBom" }
firebase-crashlytics = { module = "com.google.firebase:firebase-crashlytics" }
firebase-analytics = { module = "com.google.firebase:firebase-analytics" }
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt-ver" }
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt-ver" }

[plugins]
android-application = { id = "com.android.application", version.ref = "agp" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
android-library = { id = "com.android.library", version.ref = "agp" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
google-service = { id = "com.google.gms.google-services", version.ref = "google-service-ver" }
firebase-crashlytics = { id = "com.google.firebase.crashlytics", version.ref = "crashlytic-ver" }
hilt = { id = "com.google.dagger.hilt.android", version.ref = "hilt-ver" }
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp-ver" }

