@startuml
(app) --> [PreInitializer]
[CrashlyticsInitializer] --> [PreInitializer]
[LoggerInitializer] --> [CrashlyticsInitializer]

component InitializerEntryPoint {
    [DependencyGraphEntryPoint]
}

[PreInitializer] --> [DependencyGraphEntryPoint]
@enduml